[build-system]
requires = [
    "setuptools>=58.0.0",
    "setuptools_scm>=6.2",
    "wheel>=0.37.0",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
# asyncio_mode = "auto"
xfail_strict = true
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
]


[tool.ruff]
line-length = 120
select = ["E", "F", "W", "C90", "I", "UP"]

# Version to target for generated code.
target-version = "py38"